version: "3"
services:
  exdiary:
    image: aceberg/exercisediary
    restart: unless-stopped
    ports:
    - 8851:8851
    volumes:
    - ./data:/data/ExerciseDiary
    environment:
      TZ: CEST    
      HOST: "0.0.0.0" 
      PORT: "8851" 
      THEME: "darkly" 
      COLOR: "dark" 
