services:
  dnsmasq:
    image: schmich/dnsmasq:2.76-r1-arm
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
