version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "6789:8081"
    volumes:
      - ./data:/downloads # <----- change location of downloads folder
