version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv
      - ENCRYPTION
    environment:
      ENCRYPTION: example
    ports:
      - "8090:8090"
    volumes:
      - ./data/:/pb_data
      - ./public/:/pb_public
