---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - tvshows:/data/tvshows # <----- change location of downloads folder
      - movies:/data/movies # <----- change location of downloads folder
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp 
      - 1900:1900/udp 
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
