---
version: '2'
services:
  homer:
    image: 'b4bz/homer:latest'
    container_name: homer
    ports:
      - 5005:8080
    volumes:
      - ./data:/www/assets
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
