---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./backups:/backups # <----- change location of downloads folder
    ports:
      - 8200:8200
    restart: unless-stopped

